FilmeRazor/Models/Filme.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FilmeRazor.Models
{
    public class Filme
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo título é obrigatório")]
        public string Titulo { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Lançamento")]
        public DateTime DataLancamento { get; set; }
        public string Genero { get; set; }

        [Display(Name = "Preço")]
        [DataType(DataType.Currency)]
        public decimal Preco { get; set; }
    }
}

FilmeRazor/Controllers/FilmeController.cs
using FilmeRazor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace FilmeRazor.Controllers
{
    [Route("api/Filme")]
    [ApiController]
    public class FilmeController : Controller
    {
        private readonly FilmeContext _db;

        [BindProperty]
        public Filme Filme { get; set; }

        public FilmeController(FilmeContext db)
        {
            _db = db;
        }

        #region API Calls

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Filmes.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var filmeDb = await _db.Filmes.FirstOrDefaultAsync(u => u.Id == id);
            if (filmeDb == null)
            {
                return Json(new { success = false, message = "Erro ao tentar excluir o registro." });
            }
            _db.Filmes.Remove(filmeDb);

            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Registro excluído com sucesso." });
        }
        #endregion
    }
}

FilmeRazor/Pages/Filme/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FilmeRazor.Pages.Filme
{
    public class IndexModel : PageModel
    {
        private readonly FilmeContext _db;

        public IndexModel(FilmeContext db)
        {
            _db = db;
        }

        public IEnumerable<FilmeRazor.Models.Filme> Filmes { get; set; }

        public async Task OnGet()
        {
            Filmes = await _db.Filmes.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var Filme = await _db.Filmes.FindAsync(id);
            if (Filme == null)
            {
                return NotFound();
            }
            _db.Filmes.Remove(Filme);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }

     
 
    }
}

FilmeRazor/Pages/Filme/InserirAtualizar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FilmeRazor.Pages.Filme
{
    public class InserirAtualizarModel : PageModel
    {
        private readonly FilmeContext _db;
        public InserirAtualizarModel(FilmeContext db)
        {
            _db = db;
        }

        [BindProperty]
        public FilmeRazor.Models.Filme Filme { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            Filme = new FilmeRazor.Models.Filme();
            if (id == null)
            {
                //create
                return Page();
            }

            //update
            Filme = await _db.Filmes.FirstOrDefaultAsync(u => u.Id == id);
            if (Filme == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {

                if (Filme.Id == 0)
                {
                    _db.Filmes.Add(Filme);
                }
                else
                {
                    _db.Filmes.Update(Filme);
                }

                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }

    }
}

FilmeRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FilmeRazor.Pages
{
    public class IndexModel : PageModel
    {
       

        

        public void OnGet()
        {

        }
    }
}

FilmeRazor/Pages/Filme/Index.cshtml
@page
@model FilmeRazor.Pages.Filme.IndexModel
<br />
<div class="container border row pt-2 mt-2">
    <div class="col-9">
        <h2 class="text-primary">Lista de Filmes</h2>
    </div>
    <div class="col-3">
        <a asp-page="InserirAtualizar" class="btn btn-primary form-control text-white">Criar Novo Filme</a>
    </div>


    <div class="col-12 border pt-2 mt-2">
        <form method="post">
            @if (Model.Filmes.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Filmes.FirstOrDefault().Id"></label>
                        </th>
                        <th>
                            <label asp-for="Filmes.FirstOrDefault().Titulo"></label>
                        </th>
                        <th>
                            <label asp-for="Filmes.FirstOrDefault().DataLancamento"></label>
                        </th>
                        <th>
                            <label asp-for="Filmes.FirstOrDefault().Genero"></label>
                        </th>
                        <th>
                            <label asp-for="Filmes.FirstOrDefault().Preco"></label>
                        </th>
                        <th>

                        </th>
                    </tr>
                    @foreach (var item in Model.Filmes)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Titulo)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.DataLancamento)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Genero)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Preco)
                            </td>
                            <td>
                                <a asp-page="InserirAtualizar" asp-route-id="@item.Id" class="btn btn-primary btn-sm text-white">Editar</a>
                                <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Deseja excluir o registro?')" class="btn btn-danger btn-sm">Excluir</button>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>Não tem Filme disponível.</p>
            }
        </form>
    </div>


    <div class="col-12" style="text-align:center">
        <br />
        <span class="h3 text-primary">OU</span>
        <br /><br />
    </div>
    <div class="col-12 border p-2 mb-2">
        <table id="tblData" class="table table-primary table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Título</th>
                    <th>Data de Lançamento</th>
                    <th>Genero</th>
                    <th>Preço</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts{ 
    <script src="~/js/filme.js"></script>
}

FilmeRazor/Pages/Filme/InserirAtualizar.cshtml
@page
@model FilmeRazor.Pages.Filme.InserirAtualizarModel

    <div class="container border   pt-2 mt-2">

        <div class="row">
            <div class="col-md-8">
                <br />
                <h2 class="text-primary">@(Model.Filme.Id!=0 ? "Editar" : "Inserir") Filme</h2>
                <br />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <input type="hidden" asp-for="Filme.Id" />
                    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Filme.Titulo"></label>
                        <input asp-for="Filme.Titulo" class="form-control" />
                        <span asp-validation-for="Filme.Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Filme.DataLancamento"></label>
                        <input asp-for="Filme.DataLancamento" class="form-control" />
                        <span asp-validation-for="Filme.DataLancamento" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Filme.Genero"></label>
                        <input asp-for="Filme.Genero" class="form-control" />
                        <span asp-validation-for="Filme.Genero" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Filme.Preco"></label>
                        <input asp-for="Filme.Preco" class="form-control" />
                        <span asp-validation-for="Filme.Preco" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <div class="col-6 ">
                            @*<input type="submit" value="Atualizar" class="btn btn-primary form-control" />*@
                            <button type="submit" class="btn btn-primary form-control">
                                @(Model.Filme.Id != 0 ? "Atualizar" : "Salvar")
                            </button>
                        </div>
                        <div class="col-6">
                            <a asp-page="Index" class="btn btn-success form-control">Voltar para Lista</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @section Scripts{
        <partial name="_ValidationScriptsPartial" />
    }

FilmeRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Tutorial DotNet";
}

<div class="text-center">
    <h1 class="display-4">Tutorial DotNet</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FilmeRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tutorial DotNet</title>
    <!-- CSS only -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Tutorial DotNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Filme/Index">Filme</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tutorial DotNet  
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>